spring:
  datasource:
    username: root
    password: qinjuan1112
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath : org/lanqiao/mapper/*Mapper.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
          mapper : debug